export const clientCompanyList = [
    'ADIDAS',
    'PUMA',
    'REEBOK',
    'MUSINSA',
    'GQ KOREA',
    'W KOREA',
    'SM ENTERTAINMENT',
    'KOZ ENTERTAINMENT',
    'WOONGJIN THINKBIG',
    'EYESMAG',
    'SOAPSEOUL',
    'UNDER ARMOUR',
    'YVES SAINT LAURANT',
    'GOLDEN GOOSE',
    'MARK GONZALES',
    'MKIT RAIN',
    'ASPARAGUS',
    'ONEHUNNNIT',
    'LABELESS',
    'NEW WAVE RECORDS',
    'NONDEFINE',
    'LUC BELAIRE',
    'THE QOOS',
];

export const clientArtistList = [
    'GLENCHECK',
    'OWEN OVADOZ',
    'KEITH APE',
    'B-FREE',
    'BLOO (블루)',
    'JUNE ONE (GLENCHECK)',
    'TAEYEON (SM ENTERTAINMENT)',
    'MAX CHANGMIN (SM ENTERTAINMENT)',
    'DVWN (KOZ ENTERTAINMENT)',
    'JEREMY QUE$T',
    'DHL',
    'DJ CONAN',
    '한국사람',
    '야화',
    'FS GREEN',
    'JINBO THE SUPERFREAK',
    'LIL CHERRY/JITO MO',
    'MBA EK',
    'BIG ONE',
    'YOUNG COCO',
];
